### PR TITLE
(MAINT) correct puppet-lint url in issue template

### PR DESCRIPTION
**Pull request by bastelfreak**
Puppet Inc forked the repo and now publishes releases from their fork.

### CODE REVIEW

**Comment by bastelfreak** [comment]
let me know if the commit msg is fine, I didn't raise a github issue first for this simple change.

**Review by michaeltlombardi — APPROVED** [review]
LGTM!

**Comment by bastelfreak** [comment]
I've zero knowledge about node, I think the CI error isn't related to this change? If so, please point me in a direction for debugging.

**Comment by chelnak** [comment]
Re kicking Ci for this PR 👍

**Comment by bastelfreak** [comment]
Hey @chelnak , if you by any chance have an idea for https://github.com/puppetlabs/puppet-editor-services/issues/323, please let me know :)

**Comment by chelnak** [comment]
@bastelfreak I'll take a look! 👍

**Comment by chelnak** [comment]
P.S. @bastelfreak, thanks for this contribution. 🚀

**Pull request merged**
