### PR TITLE
(maint) Update CI to point to main branch

### PR DESCRIPTION
**Pull request by jpogran**
This commit updates CI to point to the main branch to trigger workflows

### CODE REVIEW

**Comment by glennsarti** [comment]
Self Merge when ready!

**Comment by glennsarti** [comment]
Do you need to update Travis and Appveyor to use main?

**Comment by jpogran** [comment]
We haven't had appveyor or travis running on this repo since the move :(

**Comment by glennsarti** [comment]
> We haven't had appveyor or travis running on this repo since the move :(

Delete em or setup em up?

**Comment by jpogran** [comment]
I don't see the value in keeping them for this repo when we have github actions running tests on the three platforms and performing the release

**Comment by glennsarti** [comment]
Agreed.... Delete em

**Pull request merged**
